<?php

declare(strict_types=1);

namespace OpenRTB\Tests\v3;

use PHPUnit\Framework\TestCase;
use OpenRTB\v3\Context\Device;
use OpenRTB\v3\Context\Context;
use OpenRTB\v3\Context\Source;
use OpenRTB\v3\Enums\AuctionType;
use OpenRTB\v3\Impression\Item;
use OpenRTB\v3\Request;
use OpenRTB\v3\Util\RequestBuilder;

/**
 * @covers \OpenRTB\v3\Util\RequestBuilder
 * @covers \OpenRTB\v3\Request
 */
class BuilderTest extends TestCase
{
    public function testFullRequestBuild(): void
    {
        $builder = new RequestBuilder();

        $item = new Item();
        $item->setId('item-123');

        $device = new Device();
        $device->setIp('127.0.0.1');

        $context = new Context();
        $context->setDevice($device);

        $source = new Source();
        $source->setTid('tid-abc');

        $builder
            ->setId('request-abc')
            ->setTest(true)
            ->setAuctionType(AuctionType::SECOND_PRICE)
            ->setTimeout(150)
            ->setCurrencies(['USD'])
            ->setSeat(['seat-1'])
            ->setWseat(1)
            ->setCdata('cdata-string')
            ->addItem($item)
            ->setContext($context)
            ->setSource($source);

        $request = $builder->build();

        // Assert that the returned object is a Request instance
        $this->assertInstanceOf(Request::class, $request);

        // Assert that the properties were set correctly
        $this->assertEquals('request-abc', $request->getId());
        $this->assertEquals(1, $request->getTest());
        $this->assertEquals(AuctionType::SECOND_PRICE, $request->getAt());
        $this->assertEquals(150, $request->getTmax());
        $this->assertEquals(['USD'], $request->getCur());
        $this->assertEquals(['seat-1'], $request->getSeat());
        $this->assertEquals(1, $request->getWseat());
        $this->assertEquals('cdata-string', $request->getCdata());

        // Assert that the nested objects are correct
        $items = $request->getItem();
        $this->assertIsArray($items);
        $this->assertCount(1, $items);
        $this->assertSame($item, $items[0]);
        $this->assertSame($context, $request->getContext());
        $this->assertNotNull($request->getContext());
        $this->assertSame($device, $request->getContext()->getDevice());
        $this->assertNotNull($request->getContext()->getDevice());
        $this->assertEquals('127.0.0.1', $request->getContext()->getDevice()->getIp());
        $this->assertSame($source, $request->getSource());
        $this->assertNotNull($request->getSource());
        $this->assertEquals('tid-abc', $request->getSource()->getTid());

        // Assert builder proxy methods
        $json = $builder->toJson();
        $this->assertIsString($json);
        $this->assertJson($json);
        $this->assertEquals($request->toArray(), $builder->toArray());
    }

    public function testAutoGeneratedId(): void
    {
        $builder = new RequestBuilder();
        $request = $builder->build();

        $this->assertNotNull($request->getId());
        $this->assertStringStartsWith('req_', $request->getId());
    }
}
